name: dev-deployment

env:
  VITE_TECH_DOMAIN: /web/hrm/tech-domain
  DISTRIBUTION_ID: E1KPI3F9EPTKFJ

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::047719645050:role/Github-CICD
          aws-region: ap-southeast-1

      - name: Fetch secrets
        uses: dkershner6/aws-ssm-getparameters-action@v2
        with:
          parameterPairs: |
            /web/hrm/tech-domain = VITE_TECH_DOMAIN
          withDecryption: 'true'

      - name: Echo parameters
        id: fetch-params
        run: |
          echo "VITE_TECH_DOMAIN=$VITE_TECH_DOMAIN" >> .env

      - name: Sync files to S3
        run: aws s3 sync ./dist s3://trey-primary-bucket --delete

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ env.DISTRIBUTION_ID }}
          PATHS: "/*"
