name: dev-deployment

env:
  VITE_HRM_GOOGLE: hrm-google
  VITE_TREY_DOMAIN: hrm-google-secret
  AWS_REGION: ap-southeast-1
on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Fetch parameters from SSM
        uses: dkershner6/aws-ssm-getparameters-action@v2
        with:
          parameterPairs: '${{ env.VITE_HRM_GOOGLE }} = VITE_HRM_GOOGLE, hrm-google-secret = VITE_TREY_DOMAIN'
          withDecryption: 'true'

      - name: Echo parameters
        id: fetch-params
        run: |
          echo "VITE_HRM_GOOGLE=$VITE_HRM_GOOGLE" >> .env
          echo "VITE_TREY_DOMAIN=$VITE_TREY_DOMAIN" >> .env
          echo "${{env.VITE_HRM_GOOGLE}}"
          echo "${{env.VITE_TREY_DOMAIN}}"

      - name: Sync files to S3
        run: aws s3 sync dist/ s3://trey-primary-bucket --delete
