name: dev-deployment

on:
  pull_request:
    branches:
      - dev

  push:
    branches:
      - dev

jobs:
  check-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Deploy to github pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: dist/

      # - name: Clear GitHub Pages cache
      #   run: |
      #     curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
      #     https://api.github.com/repos/${{ github.repository }}/pages/cache



  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Sync files to S3
        run: aws s3 sync dist/ s3://trey-primary-bucket --delete
