name: dev-deployment

env:
  # HRM_GOOGLE: hrm-google
  # HRM_GOOGLE_SECRET: hrm-google-secret
  ACTION_STEP_DEBUG: true

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Retrieve secrets from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: my-app-secret

      - name: Debug environment variable
        run: echo "VITE_HRM_GOOGLE=$MY_APP_SECRET"

      - name: Use secrets
        run: echo "VITE_HRM_GOOGLE=$MY_APP_SECRET" >> .env

      - name: Debug all environment variables
        run: env

      # - name: Fetch parameters from SSM
      #   uses: dkershner6/aws-ssm-getparameters-action@v2
      #   with:
      #     parameterPairs: '${{ env.HRM_GOOGLE }} = HRM_GOOGLE, ${{ env.HRM_GOOGLE_SECRET }} = HRM_GOOGLE_SECRET'
      #     withDecryption: 'true'

      # - name: Echo parameters
      #   run: |
      #     echo "HRM_GOOGLE=$HRM_GOOGLE" >> .env
      #     echo "HRM_GOOGLE_SECRET=$HRM_GOOGLE_SECRET" >> .env
      #     echo "HRM_GOOGLE=$HRM_GOOGLE"
      #     echo "HRM_GOOGLE_SECRET=$HRM_GOOGLE_SECRET"

      - name: Sync files to S3
        run: aws s3 sync dist/ s3://trey-primary-bucket --delete
