name: dev-deployment

env:
  VITE_HRM_GOOGLE: ''

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Fetch parameters from SSM
        uses: dkershner6/aws-ssm-getparameters-action@v2
        with:
          parameterPairs: '/web/hrm/tech-domain=VITE_HRM_GOOGLE'
          withDecryption: 'true'

      - name: Echo parameters
        id: fetch-params
        run: |
          echo "VITE_HRM_GOOGLE=${VITE_HRM_GOOGLE}" >> .env
          echo "$VITE_HRM_GOOGLE"

      - name: Sync files to S3
        run: aws s3 sync dist/ s3://trey-primary-bucket --delete
