name: github-action-deployment

on:
  push:
    branches:
      - deploy/github-pages

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
