name: PR Notification to Telegram

on:
  pull_request:
    branches:
      - dev

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🚀 *New Pull Request Created!*%0A%0A*Title:* ${{ github.event.pull_request.title }}%0A*By:* ${{ github.event.pull_request.user.login }}%0A*Branch:* ${{ github.event.pull_request.head.ref }}%0A*PR URL:* [View Pull Request](${{ github.event.pull_request.html_url }})" \
          -d parse_mode=Markdown
